# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/joseleite/Vivado_Projects/Vivado/VeSPA_Pipeline.srcs/sources_1/bd/design_1/ip/design_1_memory_wrapper_0_0/design_1_memory_wrapper_0_0.xci
# IP: The module: 'design_1_memory_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/joseleite/Vivado_Projects/Vivado/VeSPA_Pipeline.srcs/sources_1/ip/RAM/RAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RAM || ORIG_REF_NAME==RAM} -quiet] -quiet

# XDC: /home/joseleite/Vivado_Projects/Vivado/VeSPA_Pipeline.gen/sources_1/bd/design_1/ip/design_1_memory_wrapper_0_0/design_1_memory_wrapper_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_memory_wrapper_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/joseleite/Vivado_Projects/Vivado/VeSPA_Pipeline.srcs/sources_1/bd/design_1/ip/design_1_memory_wrapper_0_0/design_1_memory_wrapper_0_0.xci
# IP: The module: 'design_1_memory_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/joseleite/Vivado_Projects/Vivado/VeSPA_Pipeline.srcs/sources_1/ip/RAM/RAM.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RAM || ORIG_REF_NAME==RAM} -quiet] -quiet

# XDC: /home/joseleite/Vivado_Projects/Vivado/VeSPA_Pipeline.gen/sources_1/bd/design_1/ip/design_1_memory_wrapper_0_0/design_1_memory_wrapper_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_memory_wrapper_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
