set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN K17 [get_ports clk]
set_property PACKAGE_PIN Y16 [get_ports rst]

set_property IOSTANDARD LVCMOS33 [get_ports rxBit]
set_property IOSTANDARD LVCMOS33 [get_ports rxEn]
set_property IOSTANDARD LVCMOS33 [get_ports txBit]
set_property IOSTANDARD LVCMOS33 [get_ports txStart]
set_property IOSTANDARD LVCMOS33 [get_ports uartEn]
set_property PACKAGE_PIN P15 [get_ports rxEn]
set_property PACKAGE_PIN V17 [get_ports txBit]
set_property PACKAGE_PIN U15 [get_ports rxBit]
set_property PACKAGE_PIN G15 [get_ports txStart]
set_property PACKAGE_PIN W13 [get_ports uartEn]

set_property IOSTANDARD LVCMOS33 [get_ports txDone]
set_property PACKAGE_PIN D18 [get_ports txDone]
