# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constr_axips2.xdc

# Block Designs: bd/ps2_design/ps2_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ps2_design || ORIG_REF_NAME==ps2_design} -quiet] -quiet

# IP: bd/ps2_design/ip/ps2_design_ps2AXI_0_0/ps2_design_ps2AXI_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ps2_design_ps2AXI_0_0 || ORIG_REF_NAME==ps2_design_ps2AXI_0_0} -quiet] -quiet

# XDC: /home/tiago/Documents/PS2 AXI/ps2_axi.gen/sources_1/bd/ps2_design/ps2_design_ooc.xdc
