

set_property IOSTANDARD LVCMOS33 [get_ports i_Clk_0]
set_property IOSTANDARD LVCMOS33 [get_ports i_Rst_0]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Data_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Data_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Data_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Data_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports i_Rx_0]
set_property IOSTANDARD LVCMOS33 [get_ports o_Err_0]
set_property IOSTANDARD LVCMOS33 [get_ports o_OnePulse_0]
set_property IOSTANDARD LVCMOS33 [get_ports o_PWMChannel1_0]
set_property IOSTANDARD LVCMOS33 [get_ports o_PWMChannel2_0]
set_property IOSTANDARD LVCMOS33 [get_ports o_PWMChannel3_0]
set_property IOSTANDARD LVCMOS33 [get_ports o_PWMChannel4_0]
set_property IOSTANDARD LVCMOS33 [get_ports o_TimerOverflow_0]
set_property IOSTANDARD LVCMOS33 [get_ports o_Tx_0]
set_property IOSTANDARD LVCMOS33 [get_ports PS2C_0]
set_property IOSTANDARD LVCMOS33 [get_ports PS2D_0]
set_property PACKAGE_PIN Y16 [get_ports i_Rst_0]
set_property PACKAGE_PIN K17 [get_ports i_Clk_0]

set_property PACKAGE_PIN W18 [get_ports {o_Data_0[3]}]
set_property PACKAGE_PIN W19 [get_ports {o_Data_0[2]}]
set_property PACKAGE_PIN N17 [get_ports {o_Data_0[1]}]
set_property PACKAGE_PIN P18 [get_ports {o_Data_0[0]}]
set_property PACKAGE_PIN N20 [get_ports {pin_0[7]}]
set_property PACKAGE_PIN P20 [get_ports {pin_0[6]}]
set_property PACKAGE_PIN T20 [get_ports {pin_0[5]}]
set_property PACKAGE_PIN U20 [get_ports {pin_0[4]}]
set_property PACKAGE_PIN V20 [get_ports {pin_0[3]}]
set_property PACKAGE_PIN G14 [get_ports {pin_0[2]}]
set_property PACKAGE_PIN M15 [get_ports {pin_0[1]}]
set_property PACKAGE_PIN M14 [get_ports {pin_0[0]}]
set_property PACKAGE_PIN R18 [get_ports o_PWMChannel2_0]
set_property PACKAGE_PIN R17 [get_ports o_PWMChannel3_0]
set_property PACKAGE_PIN V18 [get_ports o_Err_0]
set_property PACKAGE_PIN V17 [get_ports o_OnePulse_0]
set_property PACKAGE_PIN V16 [get_ports o_Tx_0]
set_property PACKAGE_PIN W16 [get_ports o_TimerOverflow_0]
set_property PACKAGE_PIN R16 [get_ports o_PWMChannel4_0]
set_property PACKAGE_PIN T19 [get_ports PS2C_0]


set_property PACKAGE_PIN K19 [get_ports int_source0_0]
set_property PACKAGE_PIN P16 [get_ports int_source1_0]
set_property PACKAGE_PIN G15 [get_ports int_source3_0]
set_property IOSTANDARD LVCMOS33 [get_ports int_source0_0]
set_property IOSTANDARD LVCMOS33 [get_ports int_source1_0]
set_property IOSTANDARD LVCMOS33 [get_ports int_source2_0]
set_property IOSTANDARD LVCMOS33 [get_ports int_source3_0]
set_property IOSTANDARD LVCMOS33 [get_ports led_teste_0]

set_property PACKAGE_PIN J15 [get_ports i_Rx_0]

set_property PACKAGE_PIN E18 [get_ports PS2D_0]

set_property PACKAGE_PIN K18 [get_ports {pin_in_0[0]}]
set_property PACKAGE_PIN W13 [get_ports {pin_in_0[1]}]
set_property PACKAGE_PIN P15 [get_ports {pin_in_0[2]}]
set_property PACKAGE_PIN H15 [get_ports {pin_in_0[3]}]
set_property PACKAGE_PIN G14 [get_ports {pin_out_0[0]}]
set_property PACKAGE_PIN M15 [get_ports {pin_out_0[1]}]
set_property PACKAGE_PIN M14 [get_ports {pin_out_0[2]}]
set_property PACKAGE_PIN A20 [get_ports {pin_out_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_in_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_in_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_in_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_in_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_out_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_out_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_out_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_out_0[0]}]

set_property PACKAGE_PIN D18 [get_ports o_PWMChannel1_0]
set_property PACKAGE_PIN V13 [get_ports led_teste_0]
set_property PACKAGE_PIN T16 [get_ports int_source2_0]
