set_property PACKAGE_PIN K17 [get_ports i_Clk]
set_property IOSTANDARD LVCMOS33 [get_ports i_Clk]
set_property IOSTANDARD LVCMOS33 [get_ports i_Rst]
set_property IOSTANDARD LVCMOS33 [get_ports o_RData]
set_property PACKAGE_PIN K18 [get_ports i_Rst]
set_property PACKAGE_PIN M14 [get_ports o_RData]

set_property PACKAGE_PIN D18 [get_ports led]
set_property IOSTANDARD LVCMOS33 [get_ports led]
set_property PACKAGE_PIN T16 [get_ports {i_IntSources[3]}]
set_property PACKAGE_PIN W13 [get_ports {i_IntSources[2]}]
set_property PACKAGE_PIN P15 [get_ports {i_IntSources[1]}]
set_property PACKAGE_PIN G15 [get_ports {i_IntSources[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_IntSources[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_IntSources[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_IntSources[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_IntSources[0]}]
