set_property -dict { PACKAGE_PIN K17   IOSTANDARD LVCMOS33 } [get_ports { i_Clk }]; #IO_L12P_T1_MRCC_35 Sch=sysclk
create_clock -add -name sys_clk_pin -period 8.00 -waveform {0 4} [get_ports { i_Clk }];

set_property IOSTANDARD LVCMOS33 [get_ports i_Rst]
set_property IOSTANDARD LVCMOS33 [get_ports o_HSync]
set_property IOSTANDARD LVCMOS33 [get_ports o_VSync]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Green[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Green[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Green[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Green[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Blue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Blue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Blue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Blue[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Red[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Red[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Red[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Red[0]}]

set_property PACKAGE_PIN K18 [get_ports i_Rst]
set_property PACKAGE_PIN V15 [get_ports {o_Red[0]}]
set_property PACKAGE_PIN W15 [get_ports {o_Red[1]}]
set_property PACKAGE_PIN T11 [get_ports {o_Red[2]}]
set_property PACKAGE_PIN T10 [get_ports {o_Red[3]}]
set_property PACKAGE_PIN W14 [get_ports {o_Blue[0]}]
set_property PACKAGE_PIN Y14 [get_ports {o_Blue[1]}]
set_property PACKAGE_PIN T12 [get_ports {o_Blue[2]}]
set_property PACKAGE_PIN U12 [get_ports {o_Blue[3]}]
set_property PACKAGE_PIN T14 [get_ports {o_Green[0]}]
set_property PACKAGE_PIN T15 [get_ports {o_Green[1]}]
set_property PACKAGE_PIN P14 [get_ports {o_Green[2]}]
set_property PACKAGE_PIN R14 [get_ports {o_Green[3]}]
set_property PACKAGE_PIN U14 [get_ports o_HSync]
set_property PACKAGE_PIN U15 [get_ports o_VSync]

#set_property PACKAGE_PIN D18 [get_ports o_Clk125M]
#set_property IOSTANDARD LVCMOS33 [get_ports o_Clk125M]
#set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
#set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
#set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
#connect_debug_port dbg_hub/clk [get_nets o_Clk125M_OBUF]