#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Mar 11 11:53:14 WET 2024
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim ps2_axi_tb_behav -key {Behavioral:sim_1:Functional:ps2_axi_tb} -tclbatch ps2_axi_tb.tcl -protoinst "protoinst_files/ps2_design.protoinst" -log simulate.log"
xsim ps2_axi_tb_behav -key {Behavioral:sim_1:Functional:ps2_axi_tb} -tclbatch ps2_axi_tb.tcl -protoinst "protoinst_files/ps2_design.protoinst" -log simulate.log

