# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/alfredo/Desktop/codigo_git/VeSPA/Vivado/VeSPA_Pipeline.srcs/sources_1/ip/RAM/RAM.xci
# IP: The module: 'RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alfredo/Desktop/codigo_git/VeSPA/Vivado/VeSPA_Pipeline.gen/sources_1/ip/RAM/RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/alfredo/Desktop/codigo_git/VeSPA/Vivado/VeSPA_Pipeline.srcs/sources_1/ip/RAM/RAM.xci
# IP: The module: 'RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alfredo/Desktop/codigo_git/VeSPA/Vivado/VeSPA_Pipeline.gen/sources_1/ip/RAM/RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
