# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Zybo_Z710.xdc

# Block Designs: bd/vespa_soc/vespa_soc.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vespa_soc || ORIG_REF_NAME==vespa_soc} -quiet] -quiet

# IP: bd/vespa_soc/ip/vespa_soc_CustomInterconnect_0_0/vespa_soc_CustomInterconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vespa_soc_CustomInterconnect_0_0 || ORIG_REF_NAME==vespa_soc_CustomInterconnect_0_0} -quiet] -quiet

# IP: bd/vespa_soc/ip/vespa_soc_UartSlave_0_0/vespa_soc_UartSlave_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vespa_soc_UartSlave_0_0 || ORIG_REF_NAME==vespa_soc_UartSlave_0_0} -quiet] -quiet

# IP: bd/vespa_soc/ip/vespa_soc_vespa_cpu_0_0/vespa_soc_vespa_cpu_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vespa_soc_vespa_cpu_0_0 || ORIG_REF_NAME==vespa_soc_vespa_cpu_0_0} -quiet] -quiet

# IP: /home/bruno/VivadoProjects/UartEchoTest/Vivado/vespa_soc/vespa_soc.gen/sources_1/bd/vespa_soc/ip/vespa_soc_vespa_cpu_0_0/src/code_memory/code_memory.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==code_memory || ORIG_REF_NAME==code_memory} -quiet] -quiet

# IP: /home/bruno/VivadoProjects/UartEchoTest/Vivado/vespa_soc/vespa_soc.gen/sources_1/bd/vespa_soc/ip/vespa_soc_vespa_cpu_0_0/src/RAM32X32B/RAM32X32B.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RAM32X32B || ORIG_REF_NAME==RAM32X32B} -quiet] -quiet

# IP: bd/vespa_soc/ip/vespa_soc_DataMemory_0_0/vespa_soc_DataMemory_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vespa_soc_DataMemory_0_0 || ORIG_REF_NAME==vespa_soc_DataMemory_0_0} -quiet] -quiet

# IP: /home/bruno/VivadoProjects/UartEchoTest/Vivado/vespa_soc/vespa_soc.gen/sources_1/bd/vespa_soc/ip/vespa_soc_DataMemory_0_0/src/VeSPA_RAM/VeSPA_RAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==VeSPA_RAM || ORIG_REF_NAME==VeSPA_RAM} -quiet] -quiet

# IP: bd/vespa_soc/ip/vespa_soc_GPIO_Slave_0_0/vespa_soc_GPIO_Slave_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vespa_soc_GPIO_Slave_0_0 || ORIG_REF_NAME==vespa_soc_GPIO_Slave_0_0} -quiet] -quiet

# IP: bd/vespa_soc/ip/vespa_soc_PS2_0_0/vespa_soc_PS2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vespa_soc_PS2_0_0 || ORIG_REF_NAME==vespa_soc_PS2_0_0} -quiet] -quiet

# IP: /home/bruno/VivadoProjects/UartEchoTest/Vivado/vespa_soc/vespa_soc.gen/sources_1/bd/vespa_soc/ip/vespa_soc_PS2_0_0/src/Ps2Fifo/Ps2Fifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ps2Fifo || ORIG_REF_NAME==Ps2Fifo} -quiet] -quiet

# IP: bd/vespa_soc/ip/vespa_soc_timerSlave_0_0/vespa_soc_timerSlave_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vespa_soc_timerSlave_0_0 || ORIG_REF_NAME==vespa_soc_timerSlave_0_0} -quiet] -quiet

# XDC: /home/bruno/VivadoProjects/UartEchoTest/Vivado/vespa_soc/vespa_soc.gen/sources_1/bd/vespa_soc/ip/vespa_soc_vespa_cpu_0_0/src/code_memory/code_memory_ooc.xdc

# XDC: /home/bruno/VivadoProjects/UartEchoTest/Vivado/vespa_soc/vespa_soc.gen/sources_1/bd/vespa_soc/ip/vespa_soc_vespa_cpu_0_0/src/RAM32X32B/RAM32X32B_ooc.xdc

# XDC: /home/bruno/VivadoProjects/UartEchoTest/Vivado/vespa_soc/vespa_soc.gen/sources_1/bd/vespa_soc/ip/vespa_soc_DataMemory_0_0/src/VeSPA_RAM/VeSPA_RAM_ooc.xdc

# XDC: /home/bruno/VivadoProjects/UartEchoTest/Vivado/vespa_soc/vespa_soc.gen/sources_1/bd/vespa_soc/ip/vespa_soc_PS2_0_0/src/Ps2Fifo/Ps2Fifo.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Ps2Fifo || ORIG_REF_NAME==Ps2Fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/bruno/VivadoProjects/UartEchoTest/Vivado/vespa_soc/vespa_soc.gen/sources_1/bd/vespa_soc/vespa_soc_ooc.xdc
