# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# IP: ip/VideoMemory/VideoMemory.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==VideoMemory || ORIG_REF_NAME==VideoMemory} -quiet] -quiet

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: /home/tiago/Desktop/VGAStuff/VGA_working/VGA/VGA.gen/sources_1/ip/VideoMemory/VideoMemory_ooc.xdc

# XDC: /home/tiago/Desktop/VGAStuff/VGA_working/VGA/VGA.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/tiago/Desktop/VGAStuff/VGA_working/VGA/VGA.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/tiago/Desktop/VGAStuff/VGA_working/VGA/VGA.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc
