#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Mar 24 10:26:04 WET 2024
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_timer_behav -key {Behavioral:sim_1:Functional:tb_timer} -tclbatch tb_timer.tcl -view /home/goncalo/vivado_projects/test_timer/timer/tb_timer_behav.wcfg -log simulate.log"
xsim tb_timer_behav -key {Behavioral:sim_1:Functional:tb_timer} -tclbatch tb_timer.tcl -view /home/goncalo/vivado_projects/test_timer/timer/tb_timer_behav.wcfg -log simulate.log

