# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mariolima/Desktop/VESPA_SOC_V2/vespa_soc/vespa_soc.srcs/sources_1/bd/vespa_soc/ip/vespa_soc_DataMemory_0_0/vespa_soc_DataMemory_0_0.xci
# IP: The module: 'vespa_soc_DataMemory_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/mariolima/Desktop/VESPA_SOC_V2/vespa_soc/vespa_soc.gen/sources_1/bd/vespa_soc/ip/vespa_soc_DataMemory_0_0/src/VeSPA_RAM/VeSPA_RAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==VeSPA_RAM || ORIG_REF_NAME==VeSPA_RAM} -quiet] -quiet

# XDC: /home/mariolima/Desktop/VESPA_SOC_V2/vespa_soc/vespa_soc.gen/sources_1/bd/vespa_soc/ip/vespa_soc_DataMemory_0_0/src/VeSPA_RAM/VeSPA_RAM_ooc.xdc

# IP: /home/mariolima/Desktop/VESPA_SOC_V2/vespa_soc/vespa_soc.srcs/sources_1/bd/vespa_soc/ip/vespa_soc_DataMemory_0_0/vespa_soc_DataMemory_0_0.xci
# IP: The module: 'vespa_soc_DataMemory_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/mariolima/Desktop/VESPA_SOC_V2/vespa_soc/vespa_soc.gen/sources_1/bd/vespa_soc/ip/vespa_soc_DataMemory_0_0/src/VeSPA_RAM/VeSPA_RAM.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==VeSPA_RAM || ORIG_REF_NAME==VeSPA_RAM} -quiet] -quiet

# XDC: /home/mariolima/Desktop/VESPA_SOC_V2/vespa_soc/vespa_soc.gen/sources_1/bd/vespa_soc/ip/vespa_soc_DataMemory_0_0/src/VeSPA_RAM/VeSPA_RAM_ooc.xdc
