# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mariolima/Desktop/VESPA_SOC_V2/vespa_soc/vespa_soc.srcs/sources_1/bd/vespa_soc/ip/vespa_soc_vespa_cpu_0_0/vespa_soc_vespa_cpu_0_0.xci
# IP: The module: 'vespa_soc_vespa_cpu_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/mariolima/Desktop/VESPA_SOC_V2/vespa_soc/vespa_soc.gen/sources_1/bd/vespa_soc/ip/vespa_soc_vespa_cpu_0_0/src/code_memory/code_memory.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==code_memory || ORIG_REF_NAME==code_memory} -quiet] -quiet

# IP: /home/mariolima/Desktop/VESPA_SOC_V2/vespa_soc/vespa_soc.gen/sources_1/bd/vespa_soc/ip/vespa_soc_vespa_cpu_0_0/src/RAM32X32B/RAM32X32B.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RAM32X32B || ORIG_REF_NAME==RAM32X32B} -quiet] -quiet

# XDC: /home/mariolima/Desktop/VESPA_SOC_V2/vespa_soc/vespa_soc.gen/sources_1/bd/vespa_soc/ip/vespa_soc_vespa_cpu_0_0/src/code_memory/code_memory_ooc.xdc

# XDC: /home/mariolima/Desktop/VESPA_SOC_V2/vespa_soc/vespa_soc.gen/sources_1/bd/vespa_soc/ip/vespa_soc_vespa_cpu_0_0/src/RAM32X32B/RAM32X32B_ooc.xdc

# IP: /home/mariolima/Desktop/VESPA_SOC_V2/vespa_soc/vespa_soc.srcs/sources_1/bd/vespa_soc/ip/vespa_soc_vespa_cpu_0_0/vespa_soc_vespa_cpu_0_0.xci
# IP: The module: 'vespa_soc_vespa_cpu_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/mariolima/Desktop/VESPA_SOC_V2/vespa_soc/vespa_soc.gen/sources_1/bd/vespa_soc/ip/vespa_soc_vespa_cpu_0_0/src/code_memory/code_memory.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==code_memory || ORIG_REF_NAME==code_memory} -quiet] -quiet

# IP: /home/mariolima/Desktop/VESPA_SOC_V2/vespa_soc/vespa_soc.gen/sources_1/bd/vespa_soc/ip/vespa_soc_vespa_cpu_0_0/src/RAM32X32B/RAM32X32B.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RAM32X32B || ORIG_REF_NAME==RAM32X32B} -quiet] -quiet

# XDC: /home/mariolima/Desktop/VESPA_SOC_V2/vespa_soc/vespa_soc.gen/sources_1/bd/vespa_soc/ip/vespa_soc_vespa_cpu_0_0/src/code_memory/code_memory_ooc.xdc

# XDC: /home/mariolima/Desktop/VESPA_SOC_V2/vespa_soc/vespa_soc.gen/sources_1/bd/vespa_soc/ip/vespa_soc_vespa_cpu_0_0/src/RAM32X32B/RAM32X32B_ooc.xdc
