# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/TestBlockDesign/TestBlockDesign.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TestBlockDesign || ORIG_REF_NAME==TestBlockDesign} -quiet] -quiet

# IP: bd/TestBlockDesign/ip/TestBlockDesign_clk_wiz_0/TestBlockDesign_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TestBlockDesign_clk_wiz_0 || ORIG_REF_NAME==TestBlockDesign_clk_wiz_0} -quiet] -quiet

# IP: bd/TestBlockDesign/ip/TestBlockDesign_rst_clk_wiz_100M_0/TestBlockDesign_rst_clk_wiz_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TestBlockDesign_rst_clk_wiz_100M_0 || ORIG_REF_NAME==TestBlockDesign_rst_clk_wiz_100M_0} -quiet] -quiet

# IP: bd/TestBlockDesign/ip/TestBlockDesign_axi_mem_intercon_0/TestBlockDesign_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TestBlockDesign_axi_mem_intercon_0 || ORIG_REF_NAME==TestBlockDesign_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/TestBlockDesign/ip/TestBlockDesign_blk_mem_gen_0_1/TestBlockDesign_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TestBlockDesign_blk_mem_gen_0_1 || ORIG_REF_NAME==TestBlockDesign_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/TestBlockDesign/ip/TestBlockDesign_axi_bram_ctrl_0_1/TestBlockDesign_axi_bram_ctrl_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TestBlockDesign_axi_bram_ctrl_0_1 || ORIG_REF_NAME==TestBlockDesign_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/TestBlockDesign/ip/TestBlockDesign_AXI4_Lite_Master_0_0/TestBlockDesign_AXI4_Lite_Master_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TestBlockDesign_AXI4_Lite_Master_0_0 || ORIG_REF_NAME==TestBlockDesign_AXI4_Lite_Master_0_0} -quiet] -quiet

# IP: /home/mariolima/Desktop/AXI_Master_Demo/AXI_Master_Demo.gen/sources_1/bd/TestBlockDesign/ip/TestBlockDesign_AXI4_Lite_Master_0_0/src/RAM32X32B/RAM32X32B.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RAM32X32B || ORIG_REF_NAME==RAM32X32B} -quiet] -quiet

# IP: /home/mariolima/Desktop/AXI_Master_Demo/AXI_Master_Demo.gen/sources_1/bd/TestBlockDesign/ip/TestBlockDesign_AXI4_Lite_Master_0_0/src/code_memory/code_memory.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==code_memory || ORIG_REF_NAME==code_memory} -quiet] -quiet

# IP: bd/TestBlockDesign/ip/TestBlockDesign_auto_pc_0/TestBlockDesign_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TestBlockDesign_auto_pc_0 || ORIG_REF_NAME==TestBlockDesign_auto_pc_0} -quiet] -quiet

# XDC: /home/mariolima/Desktop/AXI_Master_Demo/AXI_Master_Demo.gen/sources_1/bd/TestBlockDesign/ip/TestBlockDesign_clk_wiz_0/TestBlockDesign_clk_wiz_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==TestBlockDesign_clk_wiz_0 || ORIG_REF_NAME==TestBlockDesign_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/mariolima/Desktop/AXI_Master_Demo/AXI_Master_Demo.gen/sources_1/bd/TestBlockDesign/ip/TestBlockDesign_clk_wiz_0/TestBlockDesign_clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==TestBlockDesign_clk_wiz_0 || ORIG_REF_NAME==TestBlockDesign_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/mariolima/Desktop/AXI_Master_Demo/AXI_Master_Demo.gen/sources_1/bd/TestBlockDesign/ip/TestBlockDesign_clk_wiz_0/TestBlockDesign_clk_wiz_0_ooc.xdc

# XDC: /home/mariolima/Desktop/AXI_Master_Demo/AXI_Master_Demo.gen/sources_1/bd/TestBlockDesign/ip/TestBlockDesign_rst_clk_wiz_100M_0/TestBlockDesign_rst_clk_wiz_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==TestBlockDesign_rst_clk_wiz_100M_0 || ORIG_REF_NAME==TestBlockDesign_rst_clk_wiz_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/mariolima/Desktop/AXI_Master_Demo/AXI_Master_Demo.gen/sources_1/bd/TestBlockDesign/ip/TestBlockDesign_rst_clk_wiz_100M_0/TestBlockDesign_rst_clk_wiz_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==TestBlockDesign_rst_clk_wiz_100M_0 || ORIG_REF_NAME==TestBlockDesign_rst_clk_wiz_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/mariolima/Desktop/AXI_Master_Demo/AXI_Master_Demo.gen/sources_1/bd/TestBlockDesign/ip/TestBlockDesign_blk_mem_gen_0_1/TestBlockDesign_blk_mem_gen_0_1_ooc.xdc

# XDC: /home/mariolima/Desktop/AXI_Master_Demo/AXI_Master_Demo.gen/sources_1/bd/TestBlockDesign/ip/TestBlockDesign_AXI4_Lite_Master_0_0/src/RAM32X32B/RAM32X32B_ooc.xdc

# XDC: /home/mariolima/Desktop/AXI_Master_Demo/AXI_Master_Demo.gen/sources_1/bd/TestBlockDesign/ip/TestBlockDesign_AXI4_Lite_Master_0_0/src/code_memory/code_memory_ooc.xdc

# XDC: /home/mariolima/Desktop/AXI_Master_Demo/AXI_Master_Demo.gen/sources_1/bd/TestBlockDesign/ip/TestBlockDesign_auto_pc_0/TestBlockDesign_auto_pc_0_ooc.xdc

# XDC: /home/mariolima/Desktop/AXI_Master_Demo/AXI_Master_Demo.gen/sources_1/bd/TestBlockDesign/TestBlockDesign_ooc.xdc
