#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Mar 11 21:29:10 WET 2024
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim vespa_AXI_tb_behav -key {Behavioral:sim_1:Functional:vespa_AXI_tb} -tclbatch vespa_AXI_tb.tcl -protoinst "protoinst_files/TestBlockDesign.protoinst" -view /home/mariolima/Desktop/AXI_Master_Demo/AXI4_Lite_Master_TestBench_behav.wcfg -log simulate.log"
xsim vespa_AXI_tb_behav -key {Behavioral:sim_1:Functional:vespa_AXI_tb} -tclbatch vespa_AXI_tb.tcl -protoinst "protoinst_files/TestBlockDesign.protoinst" -view /home/mariolima/Desktop/AXI_Master_Demo/AXI4_Lite_Master_TestBench_behav.wcfg -log simulate.log

