# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mariolima/Desktop/vespa_git/VeSPA/Vivado/VeSPA_Pipeline.srcs/sources_1/bd/design_1/ip/design_1_CPU_0_0/design_1_CPU_0_0.xci
# IP: The module: 'design_1_CPU_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/mariolima/Desktop/vespa_git/VeSPA/Vivado/VeSPA_Pipeline.gen/sources_1/bd/design_1/ip/design_1_CPU_0_0/src/CodeMemory/CodeMemory.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CodeMemory || ORIG_REF_NAME==CodeMemory} -quiet] -quiet

# XDC: /home/mariolima/Desktop/vespa_git/VeSPA/Vivado/VeSPA_Pipeline.gen/sources_1/bd/design_1/ip/design_1_CPU_0_0/src/CodeMemory/CodeMemory_ooc.xdc

# XDC: /home/mariolima/Desktop/vespa_git/VeSPA/Vivado/VeSPA_Pipeline.gen/sources_1/bd/design_1/ip/design_1_CPU_0_0/src/Constraints.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_CPU_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/mariolima/Desktop/vespa_git/VeSPA/Vivado/VeSPA_Pipeline.srcs/sources_1/bd/design_1/ip/design_1_CPU_0_0/design_1_CPU_0_0.xci
# IP: The module: 'design_1_CPU_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/mariolima/Desktop/vespa_git/VeSPA/Vivado/VeSPA_Pipeline.gen/sources_1/bd/design_1/ip/design_1_CPU_0_0/src/CodeMemory/CodeMemory.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CodeMemory || ORIG_REF_NAME==CodeMemory} -quiet] -quiet

# XDC: /home/mariolima/Desktop/vespa_git/VeSPA/Vivado/VeSPA_Pipeline.gen/sources_1/bd/design_1/ip/design_1_CPU_0_0/src/CodeMemory/CodeMemory_ooc.xdc

# XDC: /home/mariolima/Desktop/vespa_git/VeSPA/Vivado/VeSPA_Pipeline.gen/sources_1/bd/design_1/ip/design_1_CPU_0_0/src/Constraints.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_CPU_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
