#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Jun 06 22:45:11 WEST 2024
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim SoC_tb_time_synth -key {Post-Synthesis:sim_1:Timing:SoC_tb} -tclbatch SoC_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view /home/joseleite/Vivado_Projects/Vivado/RegisterFile_TestBench_behav.wcfg -log simulate.log"
xsim SoC_tb_time_synth -key {Post-Synthesis:sim_1:Timing:SoC_tb} -tclbatch SoC_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view /home/joseleite/Vivado_Projects/Vivado/RegisterFile_TestBench_behav.wcfg -log simulate.log

