#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Jun 06 14:47:07 WEST 2024
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim SoC_tb_behav -key {Behavioral:sim_1:Functional:SoC_tb} -tclbatch SoC_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view /home/mariolima/Desktop/vespa_git/VeSPA/Vivado/RegisterFile_TestBench_behav.wcfg -log simulate.log"
xsim SoC_tb_behav -key {Behavioral:sim_1:Functional:SoC_tb} -tclbatch SoC_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view /home/mariolima/Desktop/vespa_git/VeSPA/Vivado/RegisterFile_TestBench_behav.wcfg -log simulate.log

