# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_PS2_Slave_0_0/design_1_PS2_Slave_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_PS2_Slave_0_0 || ORIG_REF_NAME==design_1_PS2_Slave_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_timerSlave_0_0/design_1_timerSlave_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_timerSlave_0_0 || ORIG_REF_NAME==design_1_timerSlave_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_DataMemory_0_0/design_1_DataMemory_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_DataMemory_0_0 || ORIG_REF_NAME==design_1_DataMemory_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_UartSlave_0_0/design_1_UartSlave_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_UartSlave_0_0 || ORIG_REF_NAME==design_1_UartSlave_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CustomInterconnect_0_0/design_1_CustomInterconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CustomInterconnect_0_0 || ORIG_REF_NAME==design_1_CustomInterconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_interruptControllerS_0_0/design_1_interruptControllerS_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_interruptControllerS_0_0 || ORIG_REF_NAME==design_1_interruptControllerS_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_GPIO_Slave_0_0/design_1_GPIO_Slave_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_GPIO_Slave_0_0 || ORIG_REF_NAME==design_1_GPIO_Slave_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CPU_0_0/design_1_CPU_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CPU_0_0 || ORIG_REF_NAME==design_1_CPU_0_0} -quiet] -quiet

# XDC: /home/mariolima/Desktop/vespa_git/VeSPA/Vivado/VeSPA_Pipeline.gen/sources_1/bd/design_1/design_1_ooc.xdc
