#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Mar 08 03:24:51 WET 2024
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim control_tb_time_synth -key {Post-Synthesis:sim_1:Timing:control_tb} -tclbatch control_tb.tcl -view /home/araujoj/Documents/VivadoProjects/uart_axi_2_register_v1/control_tb_behav.wcfg -log simulate.log"
xsim control_tb_time_synth -key {Post-Synthesis:sim_1:Timing:control_tb} -tclbatch control_tb.tcl -view /home/araujoj/Documents/VivadoProjects/uart_axi_2_register_v1/control_tb_behav.wcfg -log simulate.log

